### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by GouravSingh2580** [GouravSingh2580/Competitive-Programming#2]
Readable all Curated topics.

**Comment by 23krishna** [comment]
Hi, can you tell me what I have to update on README file?

**Comment by sohan-k** [comment]
I can do it :) @GouravSingh2580, please assign

**Comment by GouravSingh2580** [comment]
> Hi, can you tell me what I have to update on the README file?

Improve readability by adding all topics in a tabular format. Add More Functionality to it.

**Comment by 23krishna** [comment]
> > Hi, can you tell me what I have to update on the README file?
> 
> Improve readability by adding all topics in a tabular format. Add More Functionality to it.

Okay 
I will do it. Please assign to me

**Comment by skohan** [comment]
@23krishna you do first links, I'll do second half links in README

**Comment by Mayank-Khurmai** [comment]
@GouravSingh2580  Assign this to me
